server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: shop
            uri: http://shop-service:8100
            predicates:
              - Path=/api/v1/shop/**
          - id: order
            uri: http://order-service:8200
            predicates:
              - Path=/api/v1/order/**
          - id: customer
            uri: http://customer-service:8300
            predicates:
              - Path=/api/v1/customer/**
          - id: delivery
            uri: http://delivery-service:8400
            predicates:
              - Path=/api/v1/delivery/**
          - id: auth
            uri: http://auth-service:8500
            predicates:
              - Path=/api/v1/auth/**
              -
management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      base-url: http://zipkin:9411
