server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: shop
            uri: http://shop-service:80
            predicates:
              - Path=/api/v1/shop/**
          - id: order
            uri: http://order-service:80
            predicates:
              - Path=/api/v1/order/**
          - id: customer
            uri: http://customer-service:80
            predicates:
              - Path=/api/v1/customer/**
          - id: delivery
            uri: http://delivery-service:80
            predicates:
              - Path=/api/v1/delivery/**
          - id: auth
            uri: http://auth-service:80
            predicates:
              - Path=/api/v1/auth/**
              
management:
  tracing:
    sampling:
      probability: 1.0
    zipkin:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  instance:
    hostname: discovery-service
  client:
    service-url:
      defaultZone: http://discovery-service:80/eureka
